version: "3"

networks:
  loki:

volumes: 
  logs:

services:
  loki:
    image: grafana/loki:2.3.0
    ports:
      - "3100:3100"
    volumes:
      - ./config:/mnt/config
      - ./data/loki-data:/tmp/loki
      - ./data/loki-wal:/tmp/wal
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - loki

  # Container to make fake logs
  logs:
    build:
      context: docker
      dockerfile: "Dockerfile"
    volumes:
      - logs:/logs/
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - logs:/logs/
      - ./config:/mnt/config
      - ./data/promtail:/mnt/var
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config-docker.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki



