version: "3"

volumes: 
  logs:

services:
  #
  # Container to make fake logs
  #
  logs:
    build:
      context: docker/logs
      dockerfile: "Dockerfile"
    volumes:
      - logs:/logs/
    restart: "always"

  #
  # Container to continuously ping hosts.
  #
  ping:
    build:
      context: docker/ping
      dockerfile: "Dockerfile"
    environment:
      #
      # Host to ping.  Can be hostname or IP.  Space-delimited.
      # Note that DNS lookups may fail, so consider pinging some IPs...
      #
      HOSTS: "google.com amazon.com 8.8.8.8 1.1.1.1"
    volumes:
      - logs:/logs/
    restart: "always"

  #
  # Read logs from files and ingest into Loki.
  #
  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - logs:/logs/
      - ./config:/mnt/config
      - ./data/promtail:/mnt/var
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config-docker.yaml
    ports:
      - "9081:9080"
    restart: "always"

  #
  # The Loki database for storing logs.
  #
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - ./config:/mnt/config
      - ./data/loki-data:/tmp/loki
      - ./data/loki-wal:/tmp/wal
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    restart: "always"

  #
  # Grafana, for viewing via the UI.
  #
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: "always"



