version: "3"

volumes: 
  logs:

services:
  #
  # Container to make fake logs
  #
  logs:
    build:
      context: docker/logs
      dockerfile: "Dockerfile"
    volumes:
      - logs:/logs/

  #
  # Container to continuously ping hosts.
  #
  ping:
    build:
      context: docker/ping
      dockerfile: "Dockerfile"
    volumes:
      - logs:/logs/

  #
  # Read logs from files and ingest into Loki.
  #
  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - logs:/logs/
      - ./config:/mnt/config
      - ./data/promtail:/mnt/var
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config-docker.yaml

  #
  # The Loki database for storing logs.
  #
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - ./config:/mnt/config
      - ./data/loki-data:/tmp/loki
      - ./data/loki-wal:/tmp/wal
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"

  #
  # Grafana, for viewing via the UI.
  #
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"



