server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./mnt/var/positions-docker.yaml

#
# Where to send logs.
#
clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      host: docker

#
# What to read.
#
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log

- job_name: promtail

  static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs-promtail
        __path__: /logs/promtail/*.log

  pipeline_stages:
  - match:
      selector: '{job="varlogs-promtail"}'
      stages:
        - regex:
            expression: '(?P<timestamp>(\w+ \w+ \d+ \d{2}:\d{2}:\d{2} \w+ \d{4})) (?P<host>\w+)' 
        - regex:
            expression: 'count=(?P<count>(\d+))'
        - regex:
            expression: 'count2=(?P<count2>(\d+))'
        - regex:
            expression: 'count3=(?P<count3>(\d+))'
        - labels:
            test_timestamp: timestamp
            #host: host
            count: count
            count2: count2
            count3: count3
        - timestamp:
            format: UnixDate
            source: timestamp





