server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: ./mnt/var/positions-docker.yaml

#
# Where to send logs.
#
clients:
  - url: http://loki:3100/loki/api/v1/push
    external_labels:
      host: docker

#
# What to read.
#
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log

- job_name: promtail

  static_configs:
    - targets:
        - localhost
      labels:
        job: varlogs-promtail
        __path__: /logs/promtail/*.log

  pipeline_stages:
  - match:
      selector: '{job="varlogs-promtail"}'
      stages:
        - regex:
            expression: '(?P<timestamp>(\w+ \w+ +\d+ \d{2}:\d{2}:\d{2} \w+ \d{4})) (?P<hostname>\w+)' 
        #
        # We can uncomment these to have more labels, but be advised that unique streams are based
        # on labels, and a high cardinality means that we'll get "HTTP 429 Too Many Connections" errors.
        #
        # Fewer labels == better performance
        #
        #- regex:
        #    expression: 'count=(?P<count>(\d+))'
        #- regex:
        #    expression: 'count2=(?P<count2>(\d+))'
        #- regex:
        #    expression: 'count3=(?P<count3>(\d+))'
        - labels:
            hostname: hostname
            #count: count
            #count2: count2
            #count3: count3
            #test_timestamp: timestamp
        - timestamp:
            format: UnixDate
            source: timestamp





